[workspace]
resolver = "1"
members = [
    "spark-cli", 
    "spark-market-sdk", 
    "market-contract",
    "market-registry"
]

[workspace.package]
authors = ["alexey <alexnagornnyy.an@gmail.com>"]
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.79.0"

[workspace.dependencies]
anyhow = "1.0.86"
fuels = { version = "0.66.2", features = ["fuel-core-lib"] }
tokio = { version = "1.39.3", features = ["rt", "macros"] }
