[workspace]
resolver = "1"
members = [
    "spark-cli", 
    "spark-market-sdk", 
    "market-contract",
    "orderbook-contract"
]

[workspace.package]
authors = ["alexey <alexnagornnyy.an@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.75.0"

[workspace.dependencies]
anyhow = "1.0.86"
fuels = { version = "0.63.1", features = ["fuel-core-lib"] }
tokio = { version = "1.38", features = ["rt", "macros"] }
# TODO: remove src20_sdk from repo entirely
src20_sdk = { git = "https://github.com/compolabs/src-20.git", branch = "master" }

