[workspace]
resolver = "1"
members = [
    "spark-market-sdk", 
    "scripts",
    "tests",
    "utils",
]

[workspace.package]
authors = ["alexey <alexnagornnyy.an@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.75.0"

[workspace.dependencies]
anyhow = "1.0.81"
fuels = { version = "0.55.1", features = ["fuel-core-lib"] }
rand = "0.8.5"
src20_sdk = { git = "https://github.com/compolabs/src-20.git", branch = "master" }
tokio = { version = "1.12", features = ["rt", "macros"] }
