[project]
authors = ["Alexey"]
entry = "main.sw"
license = "Apache-2.0"
name = "orderbook"

[dependencies]
i64 = { git = "https://github.com/compolabs/i64" }
reentrancy = { git = "https://github.com/FuelLabs/sway-libs" }
