[package]
name = "spark-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
spark-market-sdk = { path = "../spark-market-sdk" }
fuels = { version = "0.55.0", features = ["fuel-core-lib"] }
dotenv = "0.15.0"
tokio = { version = "1.12", features = ["rt", "macros"] }
