[project]
name = "contract"
version = "0.0.0"
authors = ["Compo Labs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
fuels = { version = "0.56.0", features = ["fuel-core-lib"] }
src20_sdk = { git = "https://github.com/compolabs/src-20.git", branch = "fuels-rs-v0.56.0" }
tokio = { version = "1.12", features = ["rt", "macros"] }

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
