[project]
authors = ["ComposabilityLabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "spark-registry"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }
