[package]
name = "spark-market-sdk"
authors = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
fuels = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }

[lib]
doctest = false
test = false
